name: Maven and Rest Assured Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run-Rest-Assured-Tests:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run REST Assured Tests with Maven
        run: mvn test

      - name: Archive REST-Assured results
        uses: actions/upload-artifact@v3
        with:
          name: REST-Assured-results
          path: target/surefire-reports

      - name: Upload REST-Assured results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: REST-Assured-results
          path: target/surefire-reports